# Generated by Django 5.2.4 on 2025-08-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_team',
            name='position',
            field=models.CharField(choices=[('QA Specialist', 'QA Specialist'), ('Python Mentor', 'Python Mentor'), ('UI/UX Designer', 'UI/UX Designer'), ('JavaScript Mentor', 'JavaScript Mentor'), ('SMM Specialist', 'SMM Specialist'), ('Cybersecurity Mentor', 'Cybersecurity Mentor')], max_length=100),
        ),
    ]
