# Generated by Django 4.2.24 on 2025-09-25 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_our_team_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\+374\\d{8}$', 'Enter a valid Armenian phone number starting with +374 and followed by 8 digits.')])),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact_Us',
        ),
        migrations.DeleteModel(
            name='Get_InTouch',
        ),
    ]
