# Generated by Django 5.2.4 on 2025-08-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_our_team_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('UI/UX Design', 'UI/UX Design'), ('Cybersecurity', 'Cybersecurity'), ('QA Testing', 'QA Testing'), ('SMM', 'SMM')], max_length=50)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('lesson_duration_month', models.IntegerField()),
                ('lesson_duration_minutes', models.IntegerField()),
                ('curriculum', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.our_team')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
