# Generated by Django 4.2.23 on 2025-08-29 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_our_team_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('UI/UX Design', 'UI/UX Design'), ('Cybersecurity', 'Cybersecurity'), ('QA Testing', 'QA Testing'), ('SMM', 'SMM')], max_length=50)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('lesson_duration_month', models.IntegerField()),
                ('lesson_duration_minutes', models.IntegerField()),
                ('curriculum', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.our_team')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='lessons.course')),
            ],
        ),
    ]
