# Generated by Django 4.2.23 on 2025-08-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_our_team_link'),
        ('lessons', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutor_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_image', to='core.our_team'),
        ),
    ]
