# Generated by Django 4.2.23 on 2025-08-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_our_team_link'),
        ('lessons', '0004_course_tutor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tutor_image',
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.our_team'),
        ),
    ]
