# Generated by Django 4.2.23 on 2025-08-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_remove_course_tutor_image_alter_course_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='lessons.course'),
        ),
    ]
