# Generated by Django 4.2.23 on 2025-08-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_faq_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='lessons.course'),
        ),
    ]
